# Generated by Django 4.1.7 on 2023-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0071_alter_ethereumblock_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="safecontract",
            name="blacklisted",
            field=models.BooleanField(default=False),
        ),
    ]
